version: '2'

services:

### PHP-FPM ##############################################
  php-fpm:
    hostname: php-fpm
    container_name: ivplapp
    build: ./.docker/php-fpm
    volumes:
      - ./projects:/var/www/projects
    expose:
      - "9000"

### NGINX Server #########################################
  nginx:
    hostname: nginx
    container_name: ivplnginx
    build: ./.docker/nginx
    volumes_from:
      - php-fpm
    volumes:
      - ./projects:/var/www/projects
      - ./logs:/var/log/nginx
      - ./sites:/etc/nginx/sites-available
    ports:
      - "80:80"
    depends_on:
        - php-fpm

### MySQL ################################################
  mysql:
    hostname: mysql
    container_name: ivplmysql
    build: ./.docker/mysql
    env_file:
      - ./.docker/mysql/env
    volumes:
      - ./data/mysql:/var/lib/mysql

    ports:
      - "33061:3306"
    restart: always



### Redis ################################################
  redis:
    hostname: redis
    container_name: ivplredis
    build: ./.docker/redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"

### phpMyAdmin ###########################################
  phpmyadmin:
    hostname: phpmyadmin
    container_name: ivplphpmyadmin
    build: ./.docker/phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./.docker/phpmyadmin/themes/metro/:/var/www/html/themes/metro/
